[package]
name = "day06"
version = "0.1.0"
authors = ["Aaron Perley <aperley@apple.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
